### ISSUE TITLE
Reland  `[TUTORIAL] persistent softmax kernel`

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#1099]
01c3e984490cbff3164ef97bf79cbd36628281dc is reverted in https://github.com/intel/intel-xpu-backend-for-triton/pull/1098 with 9c6423658a5168638907caebc7b16b4c482b5cfe, as `properties["max_num_regs"]` is not available on intel backend.

Commits to reland:
```
01c3e984490cbff3164ef97bf79cbd36628281dc
a263360050e1887a2cda0c2cac811ddd3ccaab1e
a5b32a8718b64786290a030c289c899554364e53
8ffdec13e6c36e12c378c3e4ffb6df5ef27150e5
```

**Comment by chengjunlu** [comment]
This pieces of the code is to guess the occupancy of the SM on NV GPU. It try to avoid autotune overhead for tutorial but with a reasonable performance show case. It try not to over-subscribe the SM core with a reasonable parallel number of block of threads.

```Python
kernel = triton.compile(src=src, target=target, options=opts)
kernel._init_handles()
n_regs = kernel.n_regs
size_smem = kernel.metadata.shared
occupancy = NUM_REGS // (n_regs * WARP_SIZE * num_warps)
occupancy = min(occupancy, SIZE_SMEM // size_smem)
num_programs = NUM_SM * occupancy
kernels[BLOCK_SIZE] = (kernel, num_programs)
```

The Intel GPU threads dispatcher use a different schedule algorithm for XeCore because the XeCore has different implementation for the parallel threads execution. 

I think the code here is not reasonable for Intel GPU.

**Comment by victor-eds** [comment]
Investigating PVC resident kernels performance.
