### ISSUE TITLE
[#7 GEMM Performance] gemm perf of small M, big N shape reach 80%+ of XeTLA

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#1105]
align with cutlass shape list.
m,k,n = (1,5120, 13824),  (4, 4096, 12288)

**Comment by Dewei-Wang-sh** [comment]
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/110815347/6c985b97-8ffe-4ef0-a839-81adab0be845)

**Comment by quintinwang5** [comment]
For the PoC branch, we have reach the performance target.
But the PR cannot be merged due to some review comments.
1. Shape restrictions in senmantic.py for tt.dot. Seems it's not reasonable for Triton community to accept this for Intel GPU.
2. Instead of an environment variable, we need an analysis pass to decide the necessity to prefetch A. But we don not have any investigations into the details about it. So this can be done later in a new issue.
