### ISSUE TITLE
Add `spirv.target_env` attribute to Triton pipeline.

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#1235]
As discussed offline, we would like to have it merge with the existing triton attributes (e.g., require subgroup size). And we still expect to have the corresponding metadata generated in LLVMIR.

**Comment by FMarno** [comment]
Hi @whitneywhtsang,
Just checking I understand everything correctly. This change is supposed to facilitate the use of `triton_gen.sub_group_reduce` function (since you added validation [here](https://github.com/intel/intel-xpu-backend-for-triton/pull/1223/files#diff-621c5c3bbb549b50cd2f25e835b09359b117a832a64892be53fef08acb67751c)).
Since that op will likely be generated here: https://github.com/intel/intel-xpu-backend-for-triton/blob/225122127040494391d43659e0861d2a764da744/third_party/intel/lib/TritonIntelGPUToLLVM/TargetInfo.h#L44

which is called from the `ReduceOpConversion` pass https://github.com/intel/intel-xpu-backend-for-triton/blob/225122127040494391d43659e0861d2a764da744/third_party/intel/lib/TritonIntelGPUToLLVM/ReduceOpToLLVM.cpp#L467

which is added to the `TritonGPUToLLVMPipelineManager` here: https://github.com/intel/intel-xpu-backend-for-triton/blob/225122127040494391d43659e0861d2a764da744/third_party/intel/lib/TritonIntelGPUToLLVM/PipelineManager.h#L184

So I should probably add a pass to the `TritonGPUToLLVM` pipeline before the `ReduceOpConversion` pass to read the `triton_gpu` attributes and convert them to `spirv.target_env`. Does that sounds like what you had in mind?

**Comment by whitneywhtsang** [comment]
https://github.com/llvm/llvm-project/pull/90972 also uses `spirv.target_env` attribute for subgroup shuffle lowering.
The insertion of  `spirv.target_env` attribute needs to be before `-convert-gpu-to-llvm-spv` as well.
We need to collaborate with the developer who is going to work on https://github.com/intel/intel-xpu-backend-for-triton/issues/1236, to find the situatable insertion point.

**Comment by FMarno** [comment]
Update: #1270 was merged to enable #1262. This will also be useful for #1236, but may require some changes to were the attribute is added.

**Comment by victor-eds** [comment]
Can we call this done?

**Comment by whitneywhtsang** [comment]
> Can we call this done?

Can we create a new issue to track the removal of the duplication, before closing this issue? https://github.com/intel/intel-xpu-backend-for-triton/pull/1270#issuecomment-2153077428

**Comment by whitneywhtsang** [comment]
> > Can we call this done?
> 
> Can we create a new issue to track the removal of the duplication, before closing this issue? [#1270 (comment)](https://github.com/intel/intel-xpu-backend-for-triton/pull/1270#issuecomment-2153077428)

https://github.com/intel/intel-xpu-backend-for-triton/issues/1313 created.
