### ISSUE TITLE
Use `intel::mangle` in `TritonGENToLLVMPass.cpp`

### ISSUE THREAD

**Issue by victor-eds** [intel/intel-xpu-backend-for-triton#1284]
https://github.com/intel/intel-xpu-backend-for-triton/pull/1282 added `intel::mangle` in `Mangle.h` introducing simple function name mangling. `TritonGENToLLVMPass.cpp` does not use this, using a per use case basis. Refactor and use new function instead.

**Comment by jopperm** [comment]
The mangling code in `TritonGENToLLVMPass.cpp` caters to some oddities in IGC's mangling of the `intel_sub_group_tf32_tf32_matrix_mad_k8(float __vector(8), float __vector(8), float __vector(8))` function: Its arguments are mangled `Dv8_fDv8_fS0_` (= substituting the third with the second occurrence, ignoring the first) instead of `Dv8_fS_S_`. I'd argue that it doesn't make sense implement this behavior in a generic helper method.

**Comment by victor-eds** [comment]
I agree with @jopperm here. I'd say we can reject this. Any thoughts, @whitneywhtsang?

**Comment by whitneywhtsang** [comment]
@jopperm Did you verified that IGC only accepts `Dv8_fDv8_fS0_` and not `Dv8_fS_S_`? I wonder we generate `Dv8_fDv8_fS0_` by mistake.

**Comment by jopperm** [comment]
No, I didn't test which variant(s) IGC accepts, but also couldn't reproduce the failing lit test anymore, so I just put up a PR with the change.

**Comment by jopperm** [comment]
Update: PR is in review; still need to rebase and address comments.
