### ISSUE TITLE
[Productize GEMM Performance] Features

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1450]
This is the GEMM Performance features productization umbrella ticket. Before converting this ticket umbrella ticket, please:
- Add the step-by-step GEMM Performance features productization plan here.  
- Create a separate ticket for each step and list it here. For ease of tracking, prefix the ticket title with `[Productize GEMM #step_number]`
- Add the definition of done for this ticket. The definition of done may state that all commits from PoC have been merged and CI run on the main branch shows no difference on performance numbers comparing to the PoC branch 

cc: @chengjunlu, @quintinwang5, @Dewei-Wang-sh, @etiotto, @whitneywhtsang, @tdeng5, @LiyangLingIntel

**Comment by vlad-penkin** [comment]
This ticket is related to:
- #1451

**Comment by chengjunlu** [comment]
Update the status for the GEMM performance on the fallback path from the issue #878.

Already finished:
- Setup a benchmark tools and monitoring the GEMM performance in CI. 
-- #879 
- Support sub-group-size 32 for DPAS
-- #416 
- Use the 2D load/store for the both the ToP (tensor of pointers) and PoT (pointer of tensor). (Ignore: nested ToPoToP....)
-- PoT (pointer of tensor): #146 , #413 , #415
-- ToP (tensor of pointers): 
- To pipeline the loops body with heavy `tt.dot` ops with prefetching.
- Reduce the number of the convert layout between the chained dot operations.
-- Remove redundant convert layout: #894 , 


Things need to be finished:
- Use the 2D load/store for the both the ToP (tensor of pointers) and PoT (pointer of tensor).
-- #1143
-- #880
- Reduce the number of the convert layout between the chained dot operations.
-- #951
- To use the dense stride instead of warp stride in tiling the `tt.dot` operation. So that we can use packed 2D load/store to load the operands A and B. 
-- #969
- Enable the large GRF as a turnable options for GEMM performance.

**Comment by Dewei-Wang-sh** [comment]
feature needed to productize gemm with block pointer
- https://github.com/intel/intel-xpu-backend-for-triton/pull/1132
- https://github.com/intel/intel-xpu-backend-for-triton/pull/1240
- https://github.com/intel/intel-xpu-backend-for-triton/pull/1152
- https://github.com/intel/intel-xpu-backend-for-triton/pull/1137

**Comment by whitneywhtsang** [comment]
Still need to enable split barrier.

**Comment by vlad-penkin** [comment]
@whitneywhtsang what is the ticket # for enabling split barrier?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang what is the ticket # for enabling split barrier?

There was a functional failure when enabling split barrier, it is fixed in https://github.com/intel/intel-xpu-backend-for-triton/pull/1708. As commented in https://github.com/intel/intel-xpu-backend-for-triton/pull/1708#issuecomment-2253097323, there is no performance gain in GEMM geomean, so it is not enabled.
