### ISSUE TITLE
Support for pytorch 2.4

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#151]
Currently (as of Jan 17, 2024) the Triton compiler in https://github.com/intel/intel-xpu-backend-for-triton/tree/llvm-target works with a custom version of `torch 2.1.0`.  This work item has the objective to make it work with the torch 2.4 version.

**Comment by tdeng5** [comment]
This issue blocked E2E testing (PyTorch version >v2.1), promote the priority to P0.

**Comment by alexbaden** [comment]
Isn't this already resolved w/ https://github.com/intel/intel-xpu-backend-for-triton/commit/47e703580715edfa638299f15e2c638cc49e129b and #239  ?

**Comment by etiotto** [comment]
#239 brings us up to `torch 2.1.0`, we actually need support for `torch 2.4` according to the requirements we discussed with the pytorch team. Updating the issue description.

**Comment by vlad-penkin** [comment]
@etiotto the latest public pytorch release is [2.1.2](https://github.com/pytorch/pytorch/releases/tag/v2.1.2). Shall we lower priority for this issue?

**Comment by etiotto** [comment]
> @etiotto the latest public pytorch release is [2.1.2](https://github.com/pytorch/pytorch/releases/tag/v2.1.2). Shall we lower priority for this issue?

The requirement for 2.4 comes from offline discussion with our Intel pytorch team. The will need support for the latest pytorch, as they are aligning with the future torch 2.4 release.

**Comment by Jianhui-Li** [comment]
@EikanWang   We need a corresponding IPEX version which match Triton version that have the refactored front-end API changes for Pytorch.  

@chengjunlu   We also need to patch the Triton front-end so that it can dispatch the compilation flow to XPU backend.

These are on the critical path to enable Pytorch E2E testing.

**Comment by chengjunlu** [comment]
I have created some new issues to track all the tasks for supporting this requirements.

1. Upstream the changes to public Triton to support to dispatch the compilation flow to XPU backend. #307
2. Triton XPU backend runtime driver need to compatible with new IPEX. #305 
4. Triton XPU backend need to support to be built as a third-party plug-in to upstream Triton.  #170 
5. Triton XPU backend runtime need to use SYCL instead of L0. #150 
6. Triton XPU backend runtime need to compatible with oneAPI 2024.0 package instead of 2023.2. #173
