### ISSUE TITLE
` test_line_info` contains kernel which mis compiles when threads-per-warp is 16 

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#1586]
The `test_line_info` program in `python/test/unit/language/test_line_info.py` doesn't compile when the Triton kernel is executed with threads-per-warp equal to 16. To reproduce simply launch the kernel 'dot_combine' with:

```
kernel_info = kernel_dot_combine.warmup(20, grid=(1,), threads-per-warp=16)
```

**Comment by chengjunlu** [comment]
This issue is caused because of the code doesn't support deep nested layout with DPAS as root layout.
Such as chained slice->dot->dpas, `#triton_gpu.slice<{dim = 1, parent = #triton_gpu.dot_op<{opIdx = 0, parent = #mma}>}>`.

This issue is naturally going to be fixed with the LinearLayout in code lowering.

Add @hwnam831 as he has already worked on the LinearLayout.

**Comment by chengjunlu** [comment]
@hwnam831 investigated this issue. And this issue may not be solved quickly with the LL because the LL doesn't support the conversion for the DotOperand.

Assign to @chengjunlu to PR the changes for the legacy emitOffsets and emitIndicies for the nested slice->dot->dpas layout.
