### ISSUE TITLE
[test_chain_reduce]: Fails to run correctly on PVC

### ISSUE THREAD

**Issue by etiotto** [intel/intel-xpu-backend-for-triton#164]
The end-to-end core test `test_chain_reduce` run correctly on a PVC GPU when the input operand has blocked layout. However it fails when the operand has DPAS layout.

**Comment by ienkovich** [comment]
I looked through IR dumps, and from what I saw the test is failing due to optimization on LLVM IR. The problem is in a reduction that computes a row-wise sum. Each warp processes [128, 128] parts of [256, 256] tensor, so each warp computes 128 partial row sums and puts them into the shared memory. Partial sums from the same row are stored next to each other. Then we reduce those partial sums in the following way:
```
val = tmp[thread_id]
next_val = sub_group_shuffle_xor(val, 1)
sum = val + next_val
if (thread_id % 2 == 0) {
  tmp[thread_id] = sum
}
```
And this pattern repeats three more times to build 256 sums. After LLVM IR optimization this code is transformed into:
```
if (thread_id % 2 == 0) {
  val = tmp[thread_id]
  next_val = sub_group_shuffle_xor(val, 1)
  sum = val + next_val
  tmp[thread_id] = sum
} else {
  val = tmp[thread_id]
  next_val = sub_group_shuffle_xor(val, 1)
  sum = val + next_val
}
```
Such transformation is completely valid from LLVM point of view. But it breaks the code because LLVM doesn't know about implicit unconditional dependency between the original unconditional load and conditional store (through shuffle). So, now computed sum uses garbage values from neighbor lanes since loads are conditional. BTW, with DCE later applied in IGC, the problem becomes more obvious:
```
if (thread_id % 2 == 0) {
  val = tmp[thread_id]
  next_val = sub_group_shuffle_xor(val, 1)
  sum = val + next_val
  tmp[thread_id] = sum
} else {
}
```

I looked into the code generated for CUDA and it uses inline asm ops for accessing shared memory. And shared store is predicated, so they don't have control flow at all and therefore don't have problem with the optimizer:
```
  %3470 = tail call i32 asm sideeffect "@$2 ld.shared.b32 $0, [ $1 + 0 ];", "=r,r,b"(ptr addrspace(3) %3469, i1 %3467) #3
  %3471 = tail call i32 @llvm.nvvm.shfl.sync.bfly.i32(i32 -1, i32 %3470, i32 1, i32 31)
  %3472 = add i32 %3471, %3470
  %3473 = and i32 %4, 1
  %3474 = icmp eq i32 %3473, 0
  %3475 = and i1 %3467, %3474
  tail call void asm sideeffect "@$2 st.shared.b32 [ $0 + 0 ], $1;", "r,r,b"(ptr addrspace(3) %3469, i32 %3472, i1 %3475) #3
```
I don't know if they deliberately used inline asm to avoid control flow or if some other reasons were involved.

For now, it's not fully clear how to avoid the problem. Probably, there are some attributes we can use. Otherwise, we need to get rid of the control flow.

**Comment by ienkovich** [comment]
> I hit an issue similar to this one before with `_Z7barrierj()`, I solved it by setting convergent to the function (and the call site). You can try to do the same for `sub_group_shuffle_xor`. This is what I did: [pengtu/llvm-project#40](https://github.com/pengtu/llvm-project/pull/40).

Thanks! This attribute should help to resolve the problem. I'll try a patch for LLVM.

**Comment by etiotto** [comment]
The convergent arteibut should prevent LLVM to sink the call to sub_group_shuffle_xor into the if and else branches.

**Comment by ienkovich** [comment]
Fixed
