### ISSUE TITLE
[Pytorch Upstream] Intel Triton is not ready to return n_regs for a compiled_binary.

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#1641]
Hi, recently we want to follow the design of CUDA/ROCm to enable support for Inductor's dynamic_rblock_scaling, but we need to get number of registers used for a combined kernel like this:
https://github.com/pytorch/pytorch/blob/7c45476d38176c8d5b19fb379fc073dc21beba64/torch/_inductor/runtime/triton_heuristics.py#L273-L296 

But currently Intel Triton always return n_regs = 0.
Can we return the n_regs like cuda does? 

reference: ROCm is implementing dynamic_rblock_scaling like CUDA: https://github.com/pytorch/pytorch/pull/129663

**Comment by alexbaden** [comment]
I attempted to use https://spec.oneapi.io/level-zero/latest/tools/api.html#zetkernelgetprofileinfo to store register use when compiling the kernel, but I am not having success getting `zeModuleCreate` to respect the profile flag (the register count always returns 0). I looked at SYCL APIs for getting registers and was not successful there either (I don't think `privateMemory` is what we need, but I could not get that to work anyway). But, IGC is able to get the number of registers allocated as that info shows up in debug logs if the compilation fails due to register spills. We likely need to raise this with the IGC team and/or the level zero team to see if there is a known config that allows retrieving allocated registers for a kernel, or if we need to create a feature request.

**Comment by etaf** [comment]
@EikanWang  maybe we should create a feature reqeust to  IGC team and/or the level zero team for this feature?

**Comment by etaf** [comment]
Hi, @vlad-penkin , we need this feature for performance optimization, will Triton team  raise this request to the IGC team ?

**Comment by vlad-penkin** [comment]
> Hi, @vlad-penkin , we need this feature for performance optimization, will Triton team raise this request to the IGC team ?

Yes

**Comment by etiotto** [comment]
Conceptually this is similar to what Triton (for the XPU target) already does to get the spill size from IGC. The code for that is (see driver.c in the intel third_party directory):
```


![Image](https://github.com/user-attachments/assets/c70fd8f4-435a-48a3-99d7-e2b5ca2ff73e)


```

**Comment by vlad-penkin** [comment]
> @vlad-penkin can you please open a feature request for this ?
Done.

@etaf you should receive an email notification on this feature request creation

**Comment by etaf** [comment]
> > @vlad-penkin can you please open a feature request for this ?
> > Done.
> 
> @etaf you should receive an email notification on this feature request creation

Thanks.

**Comment by alexbaden** [comment]
After investigating further this issue is not applicable to us - our GPUs have a fixed set of registers per thread and we do not scale occupancy of a work group based on register pressure (unlike CUDA, which dynamically adjust registers allocated per thread and adjust parallelism down for kernels with high memory pressure). Therefore, returning 0 is appropriate here because we do not want to tell the PyTorch Inductor auto-tuner to tune based on a parameter that has no effect. 

Note that with https://github.com/intel/intel-xpu-backend-for-triton/pull/1654 we now auto-tune the GRF mode when compiling the Triton kernel to recompile with large GRF mode in the presence of register spills. I suppose we could consider doing this tuning in PyTorch Inductor instead, but that would require quite a bit more work and it is not clear what the benefit would be over what we are doing now.

@vlad-penkin I think we can close this ticket.

**Comment by etaf** [comment]
> After investigating further this issue is not applicable to us - our GPUs have a fixed set of registers per thread and we do not scale occupancy of a work group based on register pressure (unlike CUDA, which dynamically adjust registers allocated per thread and adjust parallelism down for kernels with high memory pressure). Therefore, returning 0 is appropriate here because we do not want to tell the PyTorch Inductor auto-tuner to tune based on a parameter that has no effect.
> 
> Note that with #1654 we now auto-tune the GRF mode when compiling the Triton kernel to recompile with large GRF mode in the presence of register spills. I suppose we could consider doing this tuning in PyTorch Inductor instead, but that would require quite a bit more work and it is not clear what the benefit would be over what we are doing now.
> 
> @vlad-penkin I think we can close this ticket.

Thanks @alexbaden , agree.
