### ISSUE TITLE
check the perf affect of instr  scheduling for gemm

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#1764]
Instr scheduling pass is designed for Flash Attention. We need to know its impact on GEMM cases.

**Comment by LiyangLingIntel** [comment]
`ScheduleLoad` pass on gemm cases has a bug which raise "operand #0 does not dominate this use", working on a fix.

**Comment by LiyangLingIntel** [comment]
With changes in #1919 , gemm benchmark cases get average **4%** degradation when enable `TRITON_INTEL_ENABLE_INSTR_SCHED=1`.

To remove environment flag `TRITON_INTEL_ENABLE_INSTR_SCHED` for pass enableing, we still need a extra analysis function for like register pressure based on given patterns, so that we can make decision automatically whether enable instruction scheduling in the lowering pipeline.

**Comment by LiyangLingIntel** [comment]
> With changes in [#1919](https://github.com/intel/intel-xpu-backend-for-triton/pull/1919) , gemm benchmark cases get average **4%** degradation when enable `TRITON_INTEL_ENABLE_INSTR_SCHED=1`. The perf diff varies from -11% to 2%.
> 
> To remove environment flag `TRITON_INTEL_ENABLE_INSTR_SCHED` for pass enableing, we still need a extra analysis function for like register pressure based on given patterns, so that we can make decision automatically whether enable instruction scheduling in the lowering pipeline.

The extra analysis task is tracked by https://github.com/intel/intel-xpu-backend-for-triton/issues/1920
