### ISSUE TITLE
[Local builds] `compile-pytorch-ipex.sh` : line 92: .venv/bin/activate: No such file or directory

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1975]
Steps to reproduce:
1. Clone `intel-xpu-backend-for-triton` into a separate `<new folder>`
2. Run `cd ~/<new folder>/`intel-xpu-backend-for-triton``
3. Run `./scripts/compile-pytorch-ipex.sh --upstream-pytorch --venv`

```
(xpu-py39) ./scripts/compile-pytorch-ipex.sh --upstream-pytorch --venv                                            
**** BASE is not given *****
**** Default BASE is set to /home/<user>/support ****
**** Activate virtual environment *****
./scripts/compile-pytorch-ipex.sh: line 92: .venv/bin/activate: No such file or directory
```

**Comment by alexbaden** [comment]
You need to create the env first. Compile-triton.sh will do it.

**Comment by vlad-penkin** [comment]
The reproducer above says nothing about running the `./compile-triton.sh` script. Script needs to be changed to take into the account this usage scenario.

**Comment by alexbaden** [comment]
Most people are likely `compile-pytorch-ipex.sh` via `test-triton.sh`, and you only run `test-triton.sh` after `compile-triton.sh`. If you supply `--venv` to `compile-triton.sh`, then the virtual env is created. I do not think the other scripts should attempt to create the virtualenv - if you don't have a virtualenv, then the rest of the tasks will not succeed! 
We could consider removing virtualenv creation from the script entirely. We could also consider removing `--venv` entirely, but I like it because it ensures I do not accidentally run the script in the global env, if I failed to activate my venv before running the script.

**Comment by vlad-penkin** [comment]
@alexbaden there multiple ways to address this issue, for example, the script can show informative error message with your recommendation.

**Comment by alexbaden** [comment]
Also note that we could probably remove `compile-triton.sh`, as you can build our Triton project using the same instructions as upstream (`pip install -e python`). We now use the same version of LLVM as upstream and the SPIRV Translator install is bundled into the Triton setup.py installer. If we wanted to support custom LLVM (the only remaining functionality in `compile-triton.sh`) we could make that a separate script.

**Comment by pbchekin** [comment]
In my opinion, these scripts should not create or activate venv or conda environments. Instead, they should rely on and work in any environment created by user.

**Comment by vlad-penkin** [comment]
Fully second @pbchekin opinion. These scripts shouldn't do anything with conda/venv environments creation without asking a user an explicit permission to do so.
