### ISSUE TITLE
[E2E] Add pinned `transformers` and `timm_models` to nightly wheels

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#2101]

**Comment by YarShev** [comment]
It would be great to have explanation in the issue description why we have to use pinned versions.

**Comment by pbchekin** [comment]
> It would be great to have explanation in the issue description why we have to use pinned versions.

We need to use pinned versions of E2E dependencies, because PyTorch uses them. See
* https://github.com/pytorch/pytorch/tree/main/.github/ci_commit_pins
* https://github.com/pytorch/pytorch/tree/main/.ci/docker/ci_commit_pins

Since we build nightly wheel for `torch{vision,text,audio}` for some time it is reasonable to also build nightly wheels for `timm` and `transformers`. This will allow running E2E locally.
