### ISSUE TITLE
Investigate failures from updating SPIRV-LLVM-Translator

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2247]
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/7dacb7cdedc9c01e0ce88f1f3766c42ab8f59b7c causes Triton UT failures.
To reproduce, change `lib/Target/SPIRV/spirv-llvm-translator.conf` to `7dacb7cdedc9c01e0ce88f1f3766c42ab8f59b7c`.

**Comment by vlad-penkin** [comment]
As per @whitneywhtsang the failures are caused by this commit https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/7dacb7cdedc9c01e0ce88f1f3766c42ab8f59b7c

**Comment by arunjose696** [comment]
I debugged this with setting the following env variables `export TORCHINDUCTOR_COMPILE_THREADS=1` and `export TORCH_LOGS="+dynamo"`  the issue seems to be in "7dacb7cdedc9c01e0ce88f1f3766c42ab8f59b7c" commit of spirv transalator a new SPIRV extension `SPV_KHR_untyped_pointers` 

The error occurring is 

`InvalidModule: Invalid SPIR-V module: input SPIR-V module uses unknown extension 'SPV_KHR_untyped_pointers'`

From the error message my assumption is the new extension introduced in  spirv transalator is not understood by the drivers.
