### ISSUE TITLE
[test_propagate_nan]: Fails to run correctly on PVC

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#232]
The end-to-end core test `test_propagate_nan` fails to run correctly on a PVC GPU. We need to investigate the cause of the functional problem(s).

**Comment by quintinwang5** [comment]
For `tl.PropagateNan.NONE` and `tl.PropagateNan.ALL`, we use `LLVM::MinNumOp` and `LLVM::MinimumOp` for `tl.minimum`. But they are all converted to  `OpExtInst %float %1 fmin %30 %31` because OpenCL.std does not support `the IEEE 754-2008 definition for minNum`
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/68101902/cd63499c-f4f6-41dc-baa3-31ac2fb7297a)

See this [link](https://registry.khronos.org/SPIR-V/specs/unified1/OpenCL.ExtendedInstructionSet.100.html).

`tl.maximum` is also this case.
