### ISSUE TITLE
[test_histogram]: fails to run correctly on PVC

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#261]
```
> z_torch = torch.histc(x, bins=N, min=0, max=N - 1)
RuntimeError: "histc" not implemented for 'Int'
```

**Comment by etiotto** [comment]
The error in the description seems like a problem in the XPU port of torch because `torch.histc` ought to accept a tensor of integers as input.

**Comment by etiotto** [comment]
Compilation fails because the lowering code for `tt.histogram` generates a number of `nvvm.vote.ballot.sync` operation which cannot be lowered given that we are not targeting a NVIDIA GPU.  To fix the compilation problem we need a genx operation with the same semantics as `nvvm.vote.ballot.sync`, or a combination of operations that perform the same function.

**Comment by etiotto** [comment]
@ienkovich thanks for helping with this one!
