### ISSUE TITLE
[GEMM] Performance degradation out of box

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2693]
![Screenshot 2024-11-12 184443](https://github.com/user-attachments/assets/8436ed06-ab3e-4f60-a75e-b153ee8496b2)

GEMM out of box performance has degraded from https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11769279538 to https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11787592466. For example, for 4k GEMM, it degraded by 5%. From looking at the commits between the two runs, likely it is caused by ca95a70b226a5b92c4e84a9987d920de4cc23a69, which is intended to improve GEMM of shape 4096x8x128x16384.

**Comment by ESI-SYD** [comment]
For 4k case: revert ca95a70 does not work : [run](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11814082015/job/32912433342#step:15:810)


ca95a70 should not impact non batched gemm cases because change only happened in `matmul_kernel_with_block_pointers_batched`. 

I think this maybe comes from variance, found this case come back in this [run](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11807327206/job/32893774948#step:15:810) (include ca95a70, PR triggered):

**Comment by ESI-SYD** [comment]
Close as this issue comes from variance, lower priority and tracked in #2873
