### ISSUE TITLE
[Performance] FP16 support for atomic ops

### ISSUE THREAD

**Issue by Stonepia** [intel/intel-xpu-backend-for-triton#286]
Currently, the FP16 performance on triton atomic ops is not comparable with CUDA due to hardware limitations. 

We may need to explain how much performance difference on atomic ops, or if is there any solution to mitigate the performance gap.

Since we didn't witness much performance gap during the Hugging Face model suites due to this reason, I would suggest this task be a low priority.

**Comment by chengjunlu** [comment]
I suggest you are referring the atomic reduce ops for FP16 (add, min and max). The NV gpu supports it in HW meanwhile the PVC and ATSM doesn't support it in HW.

In Triton for Intel GPU, we uses the CAS with 32bits to emulate the atomic reduce ops with spinning if the address of the atomic ops are aligned to 2xfp16. 

The performance is expected very poor because of congestion and spinning polling in kernel.

**Comment by etiotto** [comment]
> In Triton for Intel GPU, we uses the CAS with 32bits to emulate the atomic reduce ops with spinning if the address of the atomic ops are aligned to 2xfp16.

@chengjunlu The intel-llvm branch lowers Triton's atomic RMW operation to `LLVM::AtomicRMWOp` so the comment above is not valid for the new approach.

**Comment by etiotto** [comment]
Given that PVC doesn't support atomic operation on fp16 data type, this feature cannot be supported when the target GPU architecture is PVC.

**Comment by vlad-penkin** [comment]
Duplicates
- #728
