### ISSUE TITLE
Documentation please!

### ISSUE THREAD

**Issue by chsasank** [intel/intel-xpu-backend-for-triton#327]
Hi!

I am looking to understand which branch is to be used to build triton for intel GPUs. I have not been able to figure from reading README and other docs.

Would also appreciate if you can tell me how this repo actually translates triton to Intel GPUs. Are you transforming to spir-v dialect in MLIR or is it something else.

Would be happy to contribute to the project if I'm handholded a bit. I have some relevant experience.

**Comment by etiotto** [comment]
Hi @chsasank, we have 2 different implementation: one that translates Triton operators to the SPIR MLIR dialect and one that translate them to the LLVM MLIR dialect.  Moving forward the team is focusing on the *latter* approach, which is implemented in the `llvm-target` branch (which is now the default branch in this repo). This approach is closer to what OpenAI does for NVIDIA targets and so it allows us to leverage code from upstream more easily.

To build the `llvm-target` branch you will need a PVC GPU, clone the project and compile it using the `scripts/compile-triton.sh`.  In order to run tests we have a script as well: https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/scripts/test-triton.sh. The CI we use to test pull requests has more details on packages required. 

@whitneywhtsang we should add documentation on the build process we follow.

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang we should add documentation on the build process we follow.

Yup, let's update `README.md` with the scripts available.

**Comment by chsasank** [comment]
In the case of lowering to LLVM dialect, can you explain how Triton IR is lowered and how the runtime looks like? I know that spir-v can be run on level zero API/driver.

Why do I need PVC gpu to build? Will the built binary also work for arc gpu?

**Comment by etiotto** [comment]
Triton dialect is lowered to TritonGPU dialect (and other dialect). Then the TritonGPU dialect is lowered to the LLVM dialect. When the target is an NVIDIA GPU. the LLVM IR generated by the compiler will contain also inline assembly code (PTX). When the target is a PVC GPU the resulting LLVM IR does not contain any inline assembly. Inline asm is replaced by calls to intrinsic functions. 

If you want to build the OpenAI Triton project you need a NVIDIA GPU, because the compiler is currently unable to cross compile. We have not spent time (nor is in our plans) to change the compiler to make it cross compile and we are currently focusing on PVC as the GPU to support. We haven't tried to port the project to other intel GPUs.

**Comment by chsasank** [comment]
Thanks for your response. Essentially, LLVM runtime for Intel GPUs works using 'intrinsic functions' instead of inline ptx. Can you point me to more documentation about these intrinsics.

I am using Intel Arc GPU to compile the system btw. See #335 for the issues I faced in this process.

**Comment by chsasank** [comment]
@etiotto: I think I found the relevant branch from intel/llvm repo: genx. Here seems to be the diff with main branch: https://github.com/intel/llvm/compare/sycl...genx

It looks like you've defined another MLIR dialect called genx. Is there more documentation on this?

**Comment by whitneywhtsang** [comment]
> I think I found the relevant branch from intel/llvm repo: genx. Here seems to be the diff with main branch: https://github.com/intel/llvm/compare/sycl...genx

genx branch is not based out of the default branch, you can compare against the LLVM commit specified in https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/cmake/llvm-hash.txt.

> It looks like you've defined another MLIR dialect called genx. Is there more documentation on this?

https://github.com/intel/llvm/blob/genx/mlir/include/mlir/Dialect/LLVMIR/GENXOps.td contains the list of operators in GENX dialect, and their corresponding definitions.

**Comment by chsasank** [comment]
If I understand the approach here, you're using genx dialect from intel/llvm just like how triton has custom dialects but sitting in openai/triton instead (see https://triton-lang.org/main/dialects/dialects.html). Is this correct?

**Comment by whitneywhtsang** [comment]
> If I understand the approach here, you're using genx dialect from intel/llvm just like how triton has custom dialects but sitting in openai/triton instead (see https://triton-lang.org/main/dialects/dialects.html). Is this correct?

Yes, but Triton is only one of the many projects that can consume GENX dialect, it is the counterpart of NVVM dialect for Nvidia.

**Comment by whitneywhtsang** [comment]
README.md was updated with the scripts available https://github.com/intel/intel-xpu-backend-for-triton/pull/328.

@quintinwang5 is going to add the required oneAPI and GPU driver version information to README.md.  

@chsasank kindly offered to help in documenting a more detailed build process. (https://github.com/intel/intel-xpu-backend-for-triton/issues/335#issuecomment-1912474408)
