### ISSUE TITLE
Remove `TritonGPUToLLVMBase.h` to be synchronize with upstream

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#455]
OpenAI upstream commit https://github.com/intel/intel-xpu-backend-for-triton/commit/2dd9d74527f431e5e822b8e67c01900e4d0bfef3 removes `TritonGPUToLLVMBase.h`, we added `Target target` in `ConvertTritonGPUOpToLLVMPatternBase`, so `TritonGPUToLLVMBase.h` cannot be easily removed.

The upstream commit is temporarily reverted in https://github.com/intel/intel-xpu-backend-for-triton/pull/452/commits/1c917d3d246b0dacac4a5e3f23c5c061b32001f4.

This issue is to properly handle the removal of `TritonGPUToLLVMBase.h`.

**Comment by whitneywhtsang** [comment]
Do you plan to do that for all lowering patterns, or limit to the ones that we specialized for Target::GENX? 
And what happens to patterns that we specialized only partially? My main concern is when merging new commits from upstream, it could make it more difficult to ensure our copied pattern is with the updated code.

**Comment by kurapov-peter** [comment]
Only for those specialized for the target.
> And what happens to patterns that we specialized only partially?

Those will exist as they are in the upstream by default. Some duplication will be present in our implementation.
Here's a simple example https://github.com/intel/intel-xpu-backend-for-triton/compare/llvm-target...pakurapo/target-removal I suspect this might be even easier for merging since we only add stuff. It complicates tracking original changes in partially specialized ones, but only in a way that the code is now not in one place.

**Comment by etiotto** [comment]
My concern is that often we have common code after or before those `switch(target)` sections. Currently we are able to leverage code changes, improvement, bug fixes from OpenAI exactly because of the way we have specialized only some code sections. 

Factoring out functions that we have specialized in their entirety is fine. But we do not want to replace functions with our own copy if they contain common code.

**Comment by kurapov-peter** [comment]
Agreed, this is my last point from the previous comment. We can avoid duplicating by some abstraction, but that would not help with merging.

There's an option to put the target in the type converter, however the solution is not great. Conceptually, these conversions **are** different, so it makes sense to factor them out. So I wonder if the risk of missing the updates to these partially changed conversions is realizable. I found one update in the history that improves implementation, however it was a complete rewrite.

**Comment by kurapov-peter** [comment]
Putting the target into the type converter is also not an option. It is replaced by the default one in the upstream.
I tried reverting the reverted commit. Spent a couple of hours fixing conflicts, added some hacky target resolution, and still ended up with a completely broken code. Will try to do it step by step now.

**Comment by kurapov-peter** [comment]
One more find. There are regressions when I switch to the new utils implementations. I'll peel off everything without regressions and push it. Then work through the rest.

**Comment by kurapov-peter** [comment]
Alright, this doesn't make any sense to do. I'll migrate our code to Triton's current backend layout instead.
