### ISSUE TITLE
[timm] SelecSls42b only works with the older timm version

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#497]
The recommended timm version is 0.8.22.dev0, the default is 0.9.15.dev0

**Comment by Stonepia** [comment]
This issue is because your tested TIMM suite is not pinned. You could switch to the [pinned version](https://github.com/pytorch/pytorch/blob/main/.ci/docker/ci_commit_pins/timm.txt) following the [wiki](https://github.com/intel/intel-xpu-backend-for-triton/wiki/End-to-End-Test#huggingface-and-timm-models-installation) for avoiding this.

**Comment by vlad-penkin** [comment]
@Stonepia we will not use TIMM pin which is different from the top of the main trunk upstream.

**Comment by LiyangLingIntel** [comment]
@vlad-penkin I have offline synced with @Stonepia , TIMM pin should from the same branch as the benchmark script. 
If we are testing with pytorch v2.1 benchmark script, but using TIMM pin from main branch fails to run is reasonable.

**Comment by Stonepia** [comment]
To clarify, maybe you could check by this:

```
$pip list | grep timm 
timm                        0.8.22.dev0
```

That should be right, we also detected that there are other suite that overrides the original pinned version of timm.  If you encountered this, then the package is overridden,  please add an additional line to your script for re-installing the timm:

```
$ pip list | grep timm
timm                        0.9.7 
```

```
pip install "git+https://github.com/rwightman/pytorch-image-models@b9d43c7dcac1fe05e851dd7be7187b108af593d2"
```
