### ISSUE TITLE
[test_core.py::test_dot3d] fails to run correctly on PVC

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#500]

**Comment by ienkovich** [comment]
@etiotto `test_dot3d` fails for us because FMA lowering doesn't cover this case (3-d tensors). It fails for NVidia target as well if device capabilities are set to <70 to avoid MMA. I don't think we should invest in FMA support of this case just to replace it with DPAS later. We better wait for DPAS to be fully enabled for 2-d tensors and then come back to this problem.

**Comment by etiotto** [comment]
@ienkovich thanks for the investigation. I agree that we can delay the full support, given that this test case fails for NVidia as well if device capabilities are < 70. The FMA code generation strategy is a backup strategy to use when the dot operation cannot be lowered to DPAS instructions, so I think we will need to provide the FMA capabilities anyway.

**Comment by etiotto** [comment]
@LiyangLingIntel  this is important, we need to cleanup all unit test failures.
