### ISSUE TITLE
Remove Intel specific `ReduceOpToLLVM.cpp`

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#675]
Remove `third_party/intel/lib/TritonIntelGPUToLLVM/ReduceOpToLLVM.cpp` and use `lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp` instead.

**Comment by ienkovich** [comment]
Our problem in re-using common lowerings is that the common implementation of `getStackPointer` doesn't match our version. This makes it impossible to directly re-use all passes and patterns that work with the shared memory. Some way to align `getStackPointer` implementations or provide our implementation for the common code would help.

**Comment by ienkovich** [comment]
Stack pointer is not a problem anymore because shared memory loads/stores are now covered by the TargetInfo. There are still two major changes required to switch to the common version of ReduceOpToLLVM.cpp though:
1. Avoid explicit layout handling in `include/triton/Conversion/TritonGPUToLLVM/Utility.h` by using interfaces instead. We have #789 for that
2. Upstream changes from #835. Changes are not Intel-specific. Not sure if there is an existing issue for that

**Comment by hwnam831** [comment]
@pbchekin The upstream reviewers are reluctant to merge this implementation because the change only affects Intel GPUs.
Please see [triton#4120](https://github.com/triton-lang/triton/pull/4120).

**Comment by whitneywhtsang** [comment]
> @pbchekin The upstream reviewers are reluctant to merge this implementation because the change only affects Intel GPUs. Please see [triton#4120](https://github.com/triton-lang/triton/pull/4120).

Given that reason, we cannot remove intel specific `ReduceOpToLLVM.cpp`.
