### ISSUE TITLE
Investigate why sub-group-size=32 shows better performance than sub-group-size=16 on Pytorch E2E test

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#952]
Investigate why sub-group-size=32 shows better performance than sub-group-size=16 on Pytorch E2E test.

**Comment by victor-eds** [comment]
Update: reduction codegen does not downscale with subgroup size, meaning we will get worse performance with smaller subgroups. Discuss solution.

**Comment by victor-eds** [comment]
Got new numbers. Gonna discuss them and discuss priority.

**Comment by victor-eds** [comment]
This issue should be split due to its size. Split into:

https://github.com/intel/intel-xpu-backend-for-triton/issues/1368
https://github.com/intel/intel-xpu-backend-for-triton/issues/1369
https://github.com/intel/intel-xpu-backend-for-triton/issues/1370
https://github.com/intel/intel-xpu-backend-for-triton/issues/1371

**Comment by victor-eds** [comment]
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9567378950 vs https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9502013308:
- 416 total
- 16 fails 2 cases
- Both fail 42 cases
- 32 is better 20 times
- 16 is better 4 times
- Mean: 1.02x (32 is better)
- Max 32 speedup 2.12x
- Max 16 speedup 0.68x

**Comment by victor-eds** [comment]
I think we can close this already. Followup tickets created.
